name: uml
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.7.2
  - anaconda-auth=0.8.6
  - anaconda-cli-base=0.5.2
  - annotated-types=0.6.0
  - archspec=0.2.3
  - boltons=25.0.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.2.1
  - colorama=0.4.6
  - conda=25.7.0
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-pack=0.8.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - cryptography=45.0.5
  - dbus=1.16.2
  - distro=1.9.0
  - expat=2.7.1
  - fmt=9.1.0
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jeepney=0.7.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyring=25.6.0
  - ld_impl_linux-64=2.40
  - libarchive=3.7.7
  - libcurl=8.14.1
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - menuinst=2.3.1
  - more-itertools=10.3.0
  - ncurses=6.5
  - nlohmann_json=3.11.2
  - openssl=3.0.17
  - packaging=25.0
  - pcre2=10.42
  - pip=25.1
  - pkce=1.0.3
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - pthread-stubs=0.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydantic-settings=2.6.1
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pysocks=1.7.1
  - python=3.13.5
  - python-dotenv=1.1.0
  - python_abi=3.13
  - readchar=4.0.5
  - readline=8.3
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.4
  - rich=13.9.4
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.12
  - secretstorage=3.3.1
  - semver=3.0.2
  - setuptools=78.1.1
  - shellingham=1.5.0
  - simdjson=3.10.1
  - spdlog=1.11.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tomli=2.2.1
  - tqdm=4.67.1
  - truststore=0.10.1
  - typer=0.9.0
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - attrs==25.3.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.1.0
      - dill==0.4.0
      - filelock==3.13.1
      - fonttools==4.60.0
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h5py==3.14.0
      - hf-xet==1.1.10
      - huggingface-hub==0.34.4
      - jinja2==3.1.4
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.12.0.88
      - pandas==2.3.2
      - peft==0.17.1
      - pillow==11.0.0
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.1.0
      - pyarrow==21.0.0
      - pycocotools==2.0.10
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.38.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - tokenizers==0.22.0
      - torch==2.8.0+cu126
      - torchtext==0.6.0
      - torchvision==0.23.0+cu126
      - transformers==4.56.1
      - triton==3.4.0
      - tzdata==2025.2
      - uv==0.8.19
      - wandb==0.21.4
      - wcwidth==0.2.14
      - xxhash==3.5.0
      - yarl==1.20.1
