dataset: ['fgvc_aircraft']
train_shot: [-1]
seed: [1]
descriptor_type: ['gpt3_cupl']
text_augmentation: ['vanilla']
image_augmentation: ['crop']
batch_size: [32]
num_workers: [4]
vision_model: ['vit_small_patch14_dinov2.lvd142m']
language_model: ['openlm-research/open_llama_3b_v2']
return_tokens: [False]
